### ISSUE TITLE
Remove dependency on nette/nette

### ISSUE THREAD

**Issue by davidkudera** [Carrooi/Nette-Menu#14]

**Comment by fmasa** [comment]
ping @davidkudera 
Dependency on nette/nette is removed in master. Why don't you tag new version? :)

**Comment by davidkudera** [comment]
ops... I simply forgot :smile: 
I'll do it this evening, thanks for reminding me

**Comment by davidkudera** [comment]
Cleaned all dependencies for 2.0.0
