### ISSUE TITLE
Allow: module doesn't work

### ISSUE THREAD

**Issue by FigaCZ** [Carrooi/Nette-Menu#18]
When you set rights for menu item like this:

`allow:
       roles: [root]
       module: Admin`

method isAllowed() returns always true due to this OR condition in **Item.php:634**

`$this->isAllowedForModule($this->getAllowedForModule()) ||
                    $this->isAllowedForParameters($this->getAllowedForParameters())`

**Comment by davidkudera** [comment]
Hello, I would probably suggest you to use authorization by `acl`. I plan to rewrite this package completly in a near future and there'll be probably just this type of authorization (`acl`).

But of course this is a bug

**Comment by davidkudera** [comment]
There is now new concept using authorizators in 2.0.0.
