### ISSUE TITLE
Menu can't find presenter in tester environment

### ISSUE THREAD

**Issue by foxycode** [Carrooi/Nette-Menu#19]
Could be related with #16.

I am not sure if I am doing something wrong during presenter testing or this is bug in Nette-Menu. I created clean sandbox with basic implementation of my problem here: https://github.com/foxycode/menu-test

I even separated sandbox commit from implementation so you can easily see what I added: https://github.com/foxycode/menu-test/commits/master

When I run application from webserver, menu works ok and if I uncomment line here: https://github.com/foxycode/menu-test/commit/dfa7cecb80149a2636e3cd8f452895e466d04972#diff-abe130d07a7af06d68f48f8f4e67ba5dR39 even test works ok.

You don't need to run tester, just run `php tests/HomepagePresenterTest.phpt` from repository root after `composer install`.

**Comment by davidkudera** [comment]
No longer valid in 2.0.0

**Comment by foxycode** [comment]
@davidkudera Have you any change summary for 2.0? I don't see any inreleases.

**Comment by davidkudera** [comment]
Basically it would be easier for you to just read the new readme file 😉 

Whole library is rewriten in 2.0.0 so you shoudn't just composer update it in your projects - it woudn't work - one huge bc break.
